### ISSUE TITLE
Yada-discuss should be open

### ISSUE THREAD

**Issue by Frozenlock** [juxt/yada#11]
> You must be a member of this group to view and participate in it.

I think users should be able to at least see what's being discussed... if only to increase the number of potential posters.

**Comment by Frozenlock** [comment]
Any thoughts on this?

This issue should be closed if there isn't any intention of making yada-discuss open.

**Comment by malcolmsparks** [comment]
I've made the group topics viewable by public. Thanks for suggesting this.
