### ISSUE TITLE
Support proxy headers

### ISSUE THREAD

**Issue by malcolmsparks** [juxt/yada#113]
@malcolmsparks: I think yada should use the X_FORWARDED_PROTO http header defined in this rfc:
https://tools.ietf.org/html/rfc7239

**Comment by solatis** [comment]
I would like to volunteer doing this patch -- it's an issue we're running into at work (being behind a proxy without SSL), so I want to see this fixed ASAP.

It will result in breaking behavior in situations that relied on the old behavior, which might result in undesired situations (less security web services), so perhaps it's a good idea to discuss how that will be handled.

**Comment by malcolmsparks** [comment]
It would be very welcome.

Don't worry too much about breaking compatibility with this interceptor. It was disabled until quite recently because of complaints it was breaking existing applications. Affecting users have the option of disabling the interceptor completely, because now yada allows resources to tinker with the interceptor chain.

Usually it's better for someone who is directly helped by the improvement to create it, because they have the context and real-world environment in order to test it, so I'm very supportive of you going ahead with this. If you need any information or other help from me, don't hesitate to contact me.

**Comment by solatis** [comment]
Ok, great, I will be writing a patch for this soon.

**Comment by solatis** [comment]
I think this issue can be closed.
