### ISSUE TITLE
Need newer version of ring-swagger to support collections in query and form parameters

### ISSUE THREAD

**Issue by Frozenlock** [juxt/yada#14]
Yada will need at least `0.21.0-SNAPSHOT` to generate the correct swagger json for collections in query and form parameters.

Can be generated with:
`{:query {(schema/optional-key :some-key) [schema/Str]}}`

The important part is the schema inside a vector:
`[schema/Str]`

**Comment by ikitommi** [comment]
`[metosin/ring-swagger "0.21.0"]` is released now, `0.22.0` will be released in few days (with support form Schema 1.x) .

**Comment by Frozenlock** [comment]
I'm gonna go ahead and close this now... :wink:
