### ISSUE TITLE
Keeping a changelog?

### ISSUE THREAD

**Issue by danielcompton** [juxt/yada#146]
It could be helpful to see what has changed when upgrading Yada to new versions. Is this something you'd consider doing? I'm partial to http://keepachangelog.com/en/0.3.0/, but don't really mind otherwise.

**Comment by malcolmsparks** [comment]
Hi Daniel - thanks for the suggestion. Andrey Antukh made a similar appeal
last year. I'm in full agreement - it would be helpful. I'm going to start
keeping with - consider it a new year's resolution!

Regards,

Malcolm


Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training

**Comment by malcolmsparks** [comment]
See 485c48a

**Comment by danielcompton** [comment]
Thanks!
