### ISSUE TITLE
Can't use yada/swagger because of LGPL transitive dependency

### ISSUE THREAD

**Issue by kenrestivo-stem** [juxt/yada#159]
We were going to use yada/swagger at work, but can't now, because a search of the transitive depencies shows it depends on scjsv, which depends on json-schema-validator, which is LGPL, and LGPL is not allowed.

Lein tree shows:
```clojure
   [yada/swagger "1.2.1"]
     [metosin/ring-swagger "0.22.12" :exclusions [[org.clojure/clojure]]]
       [frankiesardo/linked "1.2.9"]
       [metosin/ring-http-response "0.8.0"]
       [metosin/schema-tools "0.9.0"]
       [metosin/scjsv "0.4.0"]
         [com.github.fge/json-schema-validator "2.2.6"]
           [com.github.fge/json-schema-core "1.2.5"]
             [com.github.fge/jackson-coreutils "1.8"]
             [com.github.fge/uri-template "0.9"]
               [com.github.fge/msg-simple "1.1"]
                 [com.github.fge/btf "1.2"]
```

It seems, per lein-licenses, like all the fge libraries are LGPL:
```
com.github.fge/json-schema-core - 1.2.5 - Lesser General Public License, version 3 or greater
com.github.fge/msg-simple - 1.1 - Lesser General Public License, version 3 or greater
com.github.fge/jackson-coreutils - 1.8 - Lesser General Public License, version 3 or greater
com.github.fge/uri-template - 0.9 - Lesser General Public License, version 3 or greater
com.github.fge/btf - 1.2 - Lesser General Public License, version 3 or greater
com.github.fge/json-schema-validator - 2.2.6 - Lesser General Public License, version 3 or greater
```

**Comment by kenrestivo-stem** [comment]
Also, too, you'll need to update your license for this library, as it is not accurate to say it is EPL. If it has LGPL anywhere in it, it's infected and can't be used by many corporations.

**Comment by danielcompton** [comment]
Hi @kenrestivo-stem, the GNU website suggests that depending on LGPL JARs doesn't require all dependencies be LGPL licensed. In fact, that seems to be the express purpose of the LGPL. 

https://www.gnu.org/licenses/lgpl-java.en.html
https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License

**Comment by Frozenlock** [comment]
IANAL, but from wikipedia : 

> The main difference between the GPL and the LGPL is that the latter allows the work to be linked with (in the case of a library, "used by") a non-(L)GPLed program, regardless of whether it is free software or proprietary software.[1] The non-(L)GPLed program can then be distributed under any terms if it is not a derivative work.

**Comment by kenrestivo-stem** [comment]
I found a simple workaround:

```clojure
[yada "1.2.1" :exclusions [github.fge/json-schema-validator]]
```

Which gets me out of trouble. However, our lawyers simply reject out of hand anything with GPL anywhere in it, logic be damned, and I have comply.

**Comment by marco-m** [comment]
Your lawyers should educate themselves about the difference between GPL and LGPL.
To make an example, Clojure uses the JVM, which is written is C, which is compiler on Linux systems with gcc, which uses libc, which is LGPL (with an additional clause, but still LGPL). EVERYTHING on Linux use libc, and nobody ever complained :-)

**Comment by ikitommi** [comment]
https://github.com/java-json-tools/json-schema-validator/blob/master/README.md#read-me-first

**Comment by kenrestivo-stem** [comment]
It's dual-licensed, so I think we'll be OK, thanks.

As for LGPL and libc: Google decided not to use libc and go with newlib, because it is BSD licensed. They were worried.

Some of the people being paranoid about the LGPL here come to the company from stints at Oracle, and, as you know, Oracle is adept at suing anyone over anything-- so they perhaps have some reason to be paranoid.
