### ISSUE TITLE
modular template not found for yada

### ISSUE THREAD

**Issue by xhh** [juxt/yada#16]
On [yada user guide](http://yada.juxt.pro/user-guide.html) there's a command to generate a project:

```
lein new modular yada-demo yada
```

But it gives error: `No such template: yada`. Is this template not ready yet?

**Comment by malcolmsparks** [comment]
Yes, this template is not ready yet, but is something I'm working on and
should be done in a few days.

**Comment by Macroz** [comment]
Hi! Is there a template available yet?

**Comment by malcolmsparks** [comment]
No, not yet. But juxt/edge is closer

**Comment by malcolmsparks** [comment]
Closing, because the documentation no longer makes reference to modular and https://github.com/juxt/edge is the relevant yada template.
