### ISSUE TITLE
Decoding bug in Yada (or referenced library)

### ISSUE THREAD

**Issue by ivarref** [juxt/yada#180]
Hi, and thanks for a fine library.

My co-worker @xfsnowind encountered a strange encoding bug.
I've reproduced it [here](https://github.com/ivarref/edge/commit/3ddf42a95f533b57d34f7ae93c3ce5f621521fa8#diff-904cd5ab4c87911ea95d4053ad149fdfR38) based on the edge project.

Steps to reproduce is included in the commit, but basically is:

```
git clone https://github.com/ivarref/edge.git

cd edge

boot dev

# In new terminal

curl -H "Content-Type: application/json" -d @payload.json "localhost:3000/hello-post"
```

Output from this curl command should be 
```
author is Statistisk sentralbyr�� (two garbled characters, unexpected)
producer is Statistisk sentralbyrå (Norwegian character "å", as expected)
```

The `author` from `payload.json` shows correctly in all editors I've tried it in, and I've also verified that the binary content is identical.

I have not tried to locate the exact origin of the problem --- and it may not be in Yada itself, but it does however affect Yada.

Thanks
Kind regards

**Comment by danielcompton** [comment]
I had a go at reproducing this, and could. I then found that if I edited the payload.json file by removing the space at the end of the "Labour Force Survey, 4" and saved it, that I couldn't reproduce it. I suspect that there is a file encoding issue in the JSON, as when I looked at the binary output printed by `bs/print-bytes`  `EF BF BD` shows up, which is a [telltale sign](https://www.google.co.nz/search?q=ef+bf+bd+java&oq=ef+bf+bd+java&aqs=chrome..69i57j0l5.3614j0j7&sourceid=chrome&ie=UTF-8) of encoding issues.

I suspect this is at a lower level than Yada, perhaps the JSON parser or Aleph?

**Comment by xfsnowind** [comment]
@danielcompton I tried to test the json parser, it seems works. And before json is converted to edn, it's converted to the certain type in manifold.stream, so I think maybe it's the problem of manifold or aleph!

**Comment by ivarref** [comment]
Seems the bug is in aleph or manifold. So not in yada. I am only able to reproduce it using curl (!).

**Comment by borkdude** [comment]
FWIW, we use a workaround:

```
(ns app.yada.json
  "Yada JSON generation overrides"
  {:authors ["Michiel Borkent"]}
  (:require
   [yada.body :refer [render-map render-seq]]
   [yada.json :as yada-json]))

;; Override JSON coercion with escape-non-ascii
(defmethod render-map "application/json"
  [m representation]
  (yada-json/render-map-impl m representation
                             {:yada.cheshire
                              {:escape-non-ascii true}}))

;; Override JSON coercion with escape-non-ascii
(defmethod render-seq "application/json"
  [s representation]
  (yada-json/render-seq-impl s representation
                             {:yada.cheshire
                              {:escape-non-ascii true}}))
```

**Comment by ivarref** [comment]
I've submitted it to aleph. https://github.com/ztellman/aleph/issues/348

**Comment by ivarref** [comment]
Are you sure that solves the problem @borkdude ? 
The error here is in reading requests, not in rendering responses.

**Comment by ivarref** [comment]
Yeah, so the title is incorrect, should be decoding. Sorry!

**Comment by borkdude** [comment]
I just removed my comment before you replied, sorry, understood it wrong, but for encoding we used this workaround :).

**Comment by ivarref** [comment]
No worries. Let's hope Tellman can tell what's wrong.
