### ISSUE TITLE
schema for :responses, with swagger generation

### ISSUE THREAD

**Issue by nha** [juxt/yada#197]
Ring-swagger supports schemas on replies: https://github.com/metosin/ring-swagger/blob/b5db9c8a6a02346ebbecfc8880c507a868d33a9a/test/ring/swagger/swagger2_test.clj#L86-L91
which could be useful for documentation and client generation.

Yada could support generating it from Resources.

(issue opened as per the discussion on slack)

**Comment by malcolmsparks** [comment]
Fixed
