### ISSUE TITLE
Clojure 1.9.0

### ISSUE THREAD

**Issue by malcolmsparks** [juxt/yada#199]
I’m trying out our yada app on clojure 1.9.0-beta1. I get an exception on aleph/http/multipart.clj line 30

**Comment by borkdude** [comment]
Upgrading to the newest stable Aleph solved it for me.

**Comment by marco-m** [comment]
Is this still an issue ?

**Comment by marco-m** [comment]
@malcolmsparks Is this still an issue ?

**Comment by malcolmsparks** [comment]
No. Yada works fine with Clojure 1.9.
