### ISSUE TITLE
websocket supported

### ISSUE THREAD

**Issue by rhacker** [juxt/yada#20]
Do we have websocket supported within the lib ? Or is there any other way we can get websocket working with the lib ( using aleph websocket maybe ) ?

Thanks for creating a beautiful lib.

**Comment by malcolmsparks** [comment]
Aleph supports websockets (including upgrading the http connection to a websocket). While there is no explicit support for websockets in yada, you could add websocket handlers to the same app.

If you can think of how yada could support websockets directly, please suggest it.

**Comment by rhacker** [comment]
I have the same thought regarding the approach you just mentioned. I did have some idea but I cannot remember now, I guess I will close and open this again if needed.
