### ISSUE TITLE
`:get {:response :request}` 

### ISSUE THREAD

**Issue by nha** [juxt/yada#203]
Why does
```
:get {:response (fn [ctx] (:request ctx))}
```
work but not:
```
:get {:response :request}
```
=>
```java.lang.IllegalArgumentException: Don't know how to convert class clojure.lang.Keyword into class java.lang.String```

yada 1.2.9

**Comment by danielcompton** [comment]
I think this is because the `:request` keyword is being treated as a literal return value, not a function.

**Comment by nha** [comment]
Makes complete sense - so maybe the right thing here would be to extend it to `Keyword` too?

**Comment by malcolmsparks** [comment]
Maybe, I think that would be a little surprising to devs (principle of least surprise). Is there a strong reason to support it?

**Comment by nha** [comment]
That makes sense, I'll close this issue
