### ISSUE TITLE
[juxt/iota "0.2.1"] not in clojars

### ISSUE THREAD

**Issue by tangrammer** [juxt/yada#22]
Hi Malcolm again!
I tried to start the repl with a fresh cloned yada  repo but I got this error
`Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact juxt:iota:jar:0.2.1 in central (https://repo1.maven.org/maven2/)`
and after checking in [clojars](https://clojars.org/juxt/iota) last version is still `0.2.0` ....
could you deploy last required version?

thanks in advance!
Juan

PS: anyway i'll downgrade iota version and i'll try again hopefully it's not a breaking change

**Comment by malcolmsparks** [comment]
Hi Juan!

Good to hear from you, I hope you're well. I added a 'forall' :∀ keyword to
iota, and wasn't able to release it (being offline at the time). Thanks for
reminding me - it's now on clojars.

Regards,

Malcolm

**Comment by tangrammer** [comment]
Thanks for so quick response and fix!
