### ISSUE TITLE
Update GitHub repo with website URL?

### ISSUE THREAD

**Issue by spinningarrow** [juxt/yada#239]
It would be nice if the URL to the Yada homepage (https://juxt.pro/yada/index.html) could be added next to the repo description on GitHub.

![image](https://user-images.githubusercontent.com/1797328/40709036-9354bd80-6427-11e8-9c0d-baf5d7ccba82.png)

It provides a good jumping off point for the documentation instead of having to search through the readme for it.

Can't submit a PR for it unfortunately as it's only a GitHub thing.

**Comment by malcolmsparks** [comment]
Done- thanks!
