### ISSUE TITLE
Problem when handling multipart/form-data containing quotes and/or colons ":"

### ISSUE THREAD

**Issue by ayrtonsin** [juxt/yada#242]
;this works
(def t1 "multipart/form-data; boundary=--------------------------166365206743450200466801")
=> (yada.media-type/string->media-type t1)
{:name "multipart/form-data",
 :type "multipart",
 :subtype "form-data",
 :parameters
 {"boundary" "--------------------------166365206743450200466801"},
 :quality 1.0}

;this does not
(def t2 "multipart/form-data; boundary=\"uuid:7bb7d4c2-122d-4708-9273-158cf3b7003b\"")

=> (yada.media-type/string->media-type t2)
NullPointerException   java.util.regex.Matcher.getTextLength (Matcher.java:1283)

**Comment by ayrtonsin** [comment]
for yada "1.2.11 it gives a NullPointerException , in yada 1.2.13 it returns nil

**Comment by malcolmsparks** [comment]
Released in 1.2.15
