### ISSUE TITLE
Set-Cookie header is dropped if one of the cookie values is nil

### ISSUE THREAD

**Issue by armincerf** [juxt/yada#250]
Happens when the response contains multiple cookies and one of them is a nilable value.

E.g ```:cookies {"cookie-a" "non-nil-cookie"
                       "cookie-b" optional-value}```
If optional-value is nil, cookie-a will not be in the response.

**Comment by SevereOverfl0w** [comment]
Could be solved by a development time-only spec quite nicely.

**Comment by malcolmsparks** [comment]
Care to expand?

**Comment by SevereOverfl0w** [comment]
Just that spec fits the kinds of constraints I want here:

- no (slow) extra checking added to production
- simple predicate could check for this (might even exist as part of the effort done to spec ring).

Might already be possible using the ring specs.

**Comment by runejuhl** [comment]
How do you propose to handle this? As far as I can tell from reading [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) and [MDN Set-Cookie documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie), cookies without a value aren't valid.

The `create-response` interceptor already logs a warning when cookies are invalid: https://github.com/juxt/yada/blob/master/src/yada/interceptors.clj#L393

IMO it's better to fail fast, so maybe that warning should be changed to an exception instead?
