### ISSUE TITLE
yada 1.2.16 authentication is not backwards compatible

### ISSUE THREAD

**Issue by stijnopheide** [juxt/yada#251]
When you're relying on the functionality of yada < 1.2.16 where you could pass in an authentication scheme with `{:verify your-verify-fn}`, this no longer works with yada 1.2.16.

The check in 1.2.16 fails at https://github.com/juxt/yada/blob/1.2.16/src/yada/security.clj#L103

because the authentication scheme doesn't specify a `:scheme` key. Previously you could rely on the defmethod for `nil` (https://github.com/juxt/yada/blob/1.2.16/src/yada/security.clj#L30) but this doesn't get called anymore.

**Comment by malcolmsparks** [comment]
Agree. I've reverted the README.md to 1.2.15 and will spend more time on authentication and making it backward compatible.
