### ISSUE TITLE
juxt/iota 0.2.2 not yet in clojars

### ISSUE THREAD

**Issue by stijnopheide** [juxt/yada#33]
```[juxt/iota "0.2.2"]``` is not yet in clojars, so it's impossible to run the test suite.

**Comment by stijnopheide** [comment]
it's also not on github yet. 0.2.1 neither :)

**Comment by malcolmsparks** [comment]
Fixed



Malcolm Sparks
Director

Email: malcolm@juxt.pro
Web: https://juxt.pro

JUXT LTD.
Software Consulting, Delivery, Training
