### ISSUE TITLE
Demo site doesn't compile

### ISSUE THREAD

**Issue by i-blis** [juxt/yada#46]
The repository has a dependency not met on clojars, namely `juxt.modular:co-dependency:jar:0.3.0`. 

Still if a revert it to `[juxt.modular/co-dependency "0.2.2"]` (or revert to a few commits backs), issuing `lein run` in the repository fails with:

```
Exception in thread "main" java.lang.IllegalArgumentException: Can't define method not in interfaces:
walker, compiling:(modular/component/co_dependency/schema.clj:7:1) 
```

**Comment by malcolmsparks** [comment]
Should be fixed now

**Comment by i-blis** [comment]
It fails because of unmet dependency: you probably need to push iota 0.3.0-alpha2 to clojars (when reverting to an older version, build fails).

Thanks for your efforts.
