### ISSUE TITLE
text/plain Content-Type should specify charset when rendering a string

### ISSUE THREAD

**Issue by lvh** [juxt/yada#5]
It seems to be UTF-8, but I don't know if something is specifying this explicitly somewhere or if that's just an accidental default somewhere.

Example of this going awry using httpie and a UTF-8 term:

```
➜  ~ http GET http://localhost:8090/user-guide/examples/ResourceStateWithBody/17382343
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 24
Content-Type: text/plain
Date: Thu, 14 May 2015 03:37:25 GMT
Server: Aleph/0.4.0

Your balance is à¸¿1300
```

**Comment by malcolmsparks** [comment]
Thanks, this is very useful, I'll look into it

On 14 May 2015 at 04:41, lvh (Laurens Van Houtven) <notifications@github.com
