### ISSUE TITLE
Swagger bidi match problem

### ISSUE THREAD

**Issue by timur87** [juxt/yada#53]
Hi, 

Is this a bug or am I doing something wrong?

(def route ["" {"/api" (y/swaggered
                        {:info {:title "test"
                                :version "0.1"
                                :description "Bug"}
                         :basePath "/api"}
                        ["/v1" (yada.yada/yada "a")])}])

(bidi.bidi/match-route route "/api") -> nil

(bidi.bidi/match-route route "/api/") -> {:handler #object[yada.swagger.Swaggered$reify__41225 0x35792c1 "yada.swagger.Swaggered$reify__41225@35792c1"]}

Regards,

Timur

**Comment by malcolmsparks** [comment]
You're not doing anything wrong here. The Swagger UI only matches on `/api/`, not on `/api`. However, I think you're right to be confused, it's not intuitive. Therefore I've commited this fix: https://github.com/juxt/yada/commit/5112f0893f0a448afcf73129fb31fe3c90f67115 which will be in the next yada release. Until then, access the UI with /api/
