### ISSUE TITLE
Swagger seems to fail with the new version

### ISSUE THREAD

**Issue by timur87** [juxt/yada#58]
With yada:
[yada "1.1.0-20160210.093249-22"]

The following example from the tutorial results in an exception:
["/api"
 (swaggered
  {:info {:title "Hello World!"
          :version "1.0"
          :description "A greetings service"}
   :basePath "/api"}
  ["/greetings"
   [
    ["/hello" (yada "Hello World!\n")]
    ["/goodbye" (yada "Goodbye!\n")]
    ]
   ])]

Exception:

                   RT.java:  947  clojure.lang.RT/nthFrom
                   RT.java:  897  clojure.lang.RT/nth
                 bidi.cljc:  387  bidi.bidi$route_seq/invokeStatic
                 bidi.cljc:  387  bidi.bidi$route_seq/invoke
                 bidi.cljc:  391  bidi.bidi$route_seq/invokeStatic
                 bidi.cljc:  387  bidi.bidi$route_seq/invoke
               swagger.clj:   89  yada.swagger/swagger-spec
               swagger.clj:   87  yada.swagger/swagger-spec
               RestFn.java:  425  clojure.lang.RestFn/invoke
               swagger.clj:  172  yada.swagger/swaggered
               swagger.clj:  171  yada.swagger/swaggered
               RestFn.java:  423  clojure.lang.RestFn/invoke

**Comment by malcolmsparks** [comment]
The args have been switched. Routes first, then swagger metadata. Sorry for the break, there's a reason for this.
