### ISSUE TITLE
Content Security problems with the yada website

### ISSUE THREAD

**Issue by Frozenlock** [juxt/yada#61]
Both Chromium and Firefox refuses to load a bunch of resources because of this.

Example error message from the console:

> Refused to load the stylesheet 'http://yada.juxt.pro/bootstrap/css/bootstrap.min.css' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by malcolmsparks** [comment]
Sorry about these problems. I'm releasing a new yada version that backs out
these headers. Will post again here when available.

**Comment by malcolmsparks** [comment]
I've backed out those headers in the latest release and will do some more
thorough testing before restoring them.

**Comment by solatis** [comment]
Has this been fixed in #114 ?

**Comment by Frozenlock** [comment]
Looks fixed.
