### ISSUE TITLE
Testing function `response-for` doesn't accept map responses

### ISSUE THREAD

**Issue by Frozenlock** [juxt/yada#64]
The testing function `response-for` (as described in the [manual](http://yada.juxt.pro/manual/235_testing.md)) chokes on maps:

```
IllegalArgumentException Don't know how to convert class clojure.lang.PersistentArrayMap into class java.lang.String  byte-streams/convert (byte_streams.clj:196)
```

**Comment by Frozenlock** [comment]
Nevermind, I was returning a collection of maps (the result of `for`). Adding an outer map solves the issue.

**Comment by malcolmsparks** [comment]
Thanks for this report.  It's prompted me to take a longer look at
response-for and how it can be improved. They'll be a big improvement in
the next release.
