### ISSUE TITLE
Is there any documentation, usage examples or sample code?

### ISSUE THREAD

**Issue by danielytics** [juxt/yada#7]
From reading the readme yada sounds really cool and something I feel I'd be very interested in, but I'm having a hard time figuring it out from the tests and source. I see there is a bunch of code in `/dev/src/yada/dev` and I'm slowly piecing it together, but as its quite dense with little commenting and few docstrings its quite a bit of detective work to figure out whats what and why.

Is there any other  sample/example code or other documentation available anywhere?

Any and all help appreciated!

**Comment by malchmih** [comment]
http://yada.juxt.pro/index.html
Got it from Clojure Google Group announcement.

**Comment by danielytics** [comment]
Oh! I  didn't see this. Thanks very much. I'll close this issue :)

**Comment by malcolmsparks** [comment]
Nice to see you here Dan. The user-guide has gradually become a much more useful doc than the README.md - I've added a link in the README.md to point to it. Sorry for not making it clearer before.

**Comment by danielytics** [comment]
Thanks Malcolm,

I've read through the entire user guide now and it's pretty clear. Very
nice!

Yada looks great - similar enough to liberator that it's not too alien, but
does add a lot of benefits. I'm really liking it and will be playing with
it layer today. I absolutely love how it integrates with bidi (which I've
already been using).

Great work guys!
