### ISSUE TITLE
Document dependency on Clojure 1.7?

### ISSUE THREAD

**Issue by danielytics** [juxt/yada#8]
Might be worth mentioning somewhere that this requires Clojure 1.7 (at least until 1.7 is out of beta) as it throws an exception on require otherwise. Took a little while to realise and might save others some time.

`yada.bidi` also crashes with a rather obscure exception if a version of bidi < `1.19.0` is being used (I was accidentally pulling in `1.18.9` through `juxt.modular/bidi`). Again, might be worth mentioning minimum version requirements.

**Comment by malcolmsparks** [comment]
I didn't realise there was a dependency on clojure 1.7, thanks

also,do feel free to paste exceptions here.
