### ISSUE TITLE
Problems with CORS

### ISSUE THREAD

**Issue by danielytics** [juxt/yada#9]
CORS seems to have a few issues right now. Going by this comment in the source[1], I understand this is still a work in progress, but here are the two issues I've encountered so far anyway in case its helpful:

1. I get this error when doing a cross-origin request from Chrome: `Request header field Content-Type is not allowed by Access-Control-Allow-Headers.` I was using `cljs-ajax` to perform the requests and it automatically sends `Content-Type`, I believe. Maybe the headers list used in https://github.com/juxt/yada/blob/master/src/yada/core.clj#L129 should be pulled from the context, if provided?
2. Preflight requests trigger the authorization function (which then fails for me because the requests do not contain the credentials my auth function looks for). Perhaps `OPTION` requests should bypass the `:authorization` step?

[1] `CORS support: build this in, make allow-origin first-class, which headers should be allowed should be a hook (with default)`

**Comment by malcolmsparks** [comment]
Thanks - that's useful, I'll try to fix it soon, leaving this issue open

**Comment by tangrammer** [comment]
Hi guys, 
any updates on this?
I've seen that there is a commented line related with cors in create-response fn....
https://github.com/juxt/yada/blob/master/src/yada/core.clj#L464-L465

```
     #_(when true
                       {"access-control-allow-origin" "*"})
```

cheers!

**Comment by malcolmsparks** [comment]
I've done most of the work (see CORS demo) but it's still not quite in a releaseable state. It's been notched up one on the priority list though.

**Comment by stijnopheide** [comment]
Also ```Access-Control-Allow-Methods``` is missing from the response in the preflight request. Should it take the value of the 'Allow' header?

**Comment by malcolmsparks** [comment]
CORS is now implemented properly.

**Comment by danielytics** [comment]
Fantastic! Thanks Malcolm, Yada is really looking good :) Time for me to bring it for another test drive, I think.
